первая проверка разметки Седоны
htmlacademy-htmlcss/2159811-sedona-36 pull request #2
Opened 2023-01-31 05:19 UTC by LusienLiu

2023-01-31 07:05 UTC, jumile requested changes
Юля, все очень хорошо. Замечания есть, конечно, но в целом все получилось. Молодец!

2023-01-31 07:05 UTC, jumile commented on index.html
> +    <div class="logo-of-sedona">
Возможно, здесь div будет лишней оберткой. Можно просто ссылку оставить.

2023-01-31 07:05 UTC, jumile commented on index.html
> +        <a class="navigation-link" href="index_hotels.html">Гостиницы</a>
Название файла лучше поменять - catalog.html или hotels.html

2023-01-31 07:05 UTC, jumile commented on index.html
> +    <img class="hero-mountains" src="#" alt="Красные горы в Седоне.">
Это будет фон, потому что декоративное изображение.

2023-01-31 07:05 UTC, jumile commented on index.html
> +          </li>
Отлично!

2023-01-31 07:05 UTC, jumile commented on index.html
> +  <section class="advantages">
Возможно, всем section на странице имеет смысл сделать разные классы - если сами блоки разные. Я вот здесь пока не уверена, что один класс сгодится для всех трех блоков.

2023-01-31 07:05 UTC, jumile commented on index.html
> +      <form class="subscribe-form" action="https://echo.htmlacademy.ru" method="post"><!--Что писать в action?-->
Все правильно в action.

2023-01-31 07:05 UTC, jumile commented on index.html
> +          <label class="visually-hidden" for="user-email"Ваш e-mail</label>
for="user-email"Ваш e-mail - угловая скобка пропущена после кавычек.

2023-01-31 07:05 UTC, jumile commented on index.html
> +      <p class="phone">+7 (812) 812-12-12</p>
На телефон нужно поставить ссылку, чтобы позвонить можно было по нажатию.

2023-01-31 07:05 UTC, jumile commented on index.html
> +      <div class="logo-of-academy">
Этот div тоже может не потребоваться, как и с логотипом Седоны.

2023-01-31 07:05 UTC, jumile commented on index.html
> +  </footer>
Первая страница просто великолепно!

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <a class="navigation-link">Главная</a>
Здесь нужно добавить ссылку на index.html

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <a class="navigation-link" href="#">Гостиницы</a>
А здесь можно href удалить, это же текущая страница.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +        <form class="catalog-filter" action="#" method="get"><!--Что писать в action?-->
Здесь писать то же самое, что в форме подписки. action - это ссылка на обработчик формы. Т.е. где-то на сервере есть спец. файл, который принимает данные из формы и обрабатывает их. В нашем случае это тестовый файл от Академии, который просто показывает, какие данные придут из формы, если ее отправить.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +                <input class="control-input" type="radio" name="types" checked>
Переключателям надо еще добавить атрибут value с конкр. значением, чтобы понимать, какую радиокнопку выбрал посетитель - у них же name у всех одинаковый, поэтому нужен value.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +          <form class="price-form" action="#" method="post">
Это не отдельная форма, это еще один fieldset.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <input class="field" placeholder="0" type="number" name="price-from" id="price-form">
У каждого input должен быть label, т.е. подпись. В данном случае цена - это название всего раздела, а у текстовых полей должны быть label, чтобы было понятно, в какое поле какие данные нужно вводить. Двух одинаковых id на странице быть не может, id всегда уникален, это как имя собственное у тега. Тип number ты правильно выбрала.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +          <button class="button-clear" type="submit">Очистить</button>
У кнопки очистки тип reset. Submit - это отправка формы на сервер.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <a class="viewer-small-link" href="#">
Ссылка или кнопка? Что будет делать этот элемент?

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +      <h2>Найдено гостиниц: 38</h2>
Тут лучше сделать заголовок скрытый - что-нибудь типа "Результаты поиска", а эту фразу оформить обычным абзацем. Она по смыслу просто не похожа на заголовок.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <h4 class="hotel-card-title">Amara Resort&Spa</h4>
Уровни заголовков лучше указывать по порядку. У тебя выше h2, поэтому для названия отеля правильнее будет h3.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +          <a class="hotel-card-put-button button" href="#">В избранное</a>
Вопрос на размышление: что будут делать эти элементы (Подробнее и В избранное)?

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +
Карточки отелей лучше оформлять списком ul. Это принятая практика, мы же их перечисляем. Поэтому вместо div - li.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +          <a class="hotel-card-link" href="product.html">
Здесь не нужно указывать ничего в href, у нас же в макете нет такой страницы. Просто поставь заглушку #.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +        <ul class="pagination">
Для пагинации предпочтительнее нумерованный список, ведь порядок страниц важен?

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +            <a class="pagination-link pagination-prev pagination-disabled">
А у нас в макете нет предыдущей страницы)) И следующей тоже.

2023-01-31 07:05 UTC, jumile commented on index_hotels.html
> +          </li>
А вот трех точек не хватает здесь. Кстати, что они будут делать, как думаешь?

2023-01-31 08:07 UTC, LusienLiu commented on index.html
> +    <img class="hero-mountains" src="#" alt="Красные горы в Седоне.">
то есть фоновое изображение будет добавлено через css? Получается, этот тег вообще надо убрать?

2023-01-31 08:44 UTC, LusienLiu commented on index_hotels.html
> +          </li>
Оформила как ссылку на подгрузку еще страниц. хотя в пагинации на wildberries это вообще не ссылка. Но, говорят, это не показатель

2023-01-31 09:28 UTC, jumile commented on index.html
> +    <img class="hero-mountains" src="#" alt="Красные горы в Седоне.">
Да, верно.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +            <a class="navigation-link">Главная</a>
Здесь нужно добавить ссылку на index.html

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +        <form class="catalog-filter" action="#" method="get"><!--Что писать в action?-->
Здесь писать то же самое, что в форме подписки. action - это ссылка на обработчик формы. Т.е. где-то на сервере есть спец. файл, который принимает данные из формы и обрабатывает их. В нашем случае это тестовый файл от Академии, который просто показывает, какие данные придут из формы, если ее отправить.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +                <input class="control-input" type="radio" name="types" checked>
Переключателям надо еще добавить атрибут value с конкр. значением, чтобы понимать, какую радиокнопку выбрал посетитель - у них же name у всех одинаковый, поэтому нужен value.
Пример: input class="control-input" type="radio" name="types" checked value="hotel"

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +          <form class="price-form" action="#" method="post">
Это не отдельная форма, это еще один fieldset. Формы нельзя вкладывать друг в друга.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +            <input class="field" placeholder="0" type="number" name="price-from" id="price-form">
У каждого input должен быть label, т.е. подпись. В данном случае цена - это название всего раздела, а у текстовых полей должны быть label, чтобы было понятно, в какое поле какие данные нужно вводить. Двух одинаковых id на странице быть не может, id всегда уникален, это как имя собственное у тега. Тип number ты правильно выбрала.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +          <button class="button-clear" type="submit">Очистить</button>
У кнопки очистки тип reset. Submit - это отправка формы на сервер.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +            <legclaend ss="hotels-filter-title">Тип Жилья:</legend>
Было правильно, сейчас какой-то новый тег появился. Должно быть legend

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +            <form class="price-form" action="https://echo.htmlacademy.ru" method="post">
Форму надо убрать совсем. У тебя 1 форма, а здесь просто fieldset. И открывающий legend тоже с опечаткой.

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +        <p class="seslect-result">Найдено гостиниц: 38</p>
seslect-result - странное название. Тут точно нет опечатки?

2023-02-02 15:38 UTC, jumile commented on hotels.html
> +            <button class="hotel-card-put-button" href="#" type="button">В избранное</button>
Атрибут href нужно убрать, у кнопок его нет.

2023-02-02 15:44 UTC, jumile approved these changes
Супер! Ты это сделала!

2023-02-02 15:45 UTC, merged