Добавляет стили на обе страницы
htmlacademy-htmlcss/2159811-sedona-36 pull request #3
Opened 2023-02-12 06:27 UTC by LusienLiu

2023-02-12 16:35 UTC, jumile requested changes
Ну что сказать? Очень хорошо, ты молодец!
На что обратить внимание?
1) отступы в коде - где-то лишние, где-то не хватает. Не надо делать их руками, пользуйся EditorConfig: https://www.youtube.com/watch?v=wWbDC1C7JEE
2) обрати внимание, что параметры шрифта (font) не наследуются элементами форм - полями, кнопками и т.д. Поэтому нужно либо прописывать прямо font-family: "PT Sans", sans-serif; font-size: 18px, либо использовать для этих свойств ключевое слово inherit: https://developer.mozilla.org/ru/docs/Web/CSS/inherit
3) еще забыла удалить подчеркивание у ссылок пагинации.
В остальном все хорошо получилось, ты молодец. Жду поправленную версию.

2023-02-12 16:35 UTC, jumile commented on hotels.html
> +                  <input class="control-input" type="checkbox" name="Parking" checked>
parking - сделай c маленькой буквы

2023-02-12 16:35 UTC, jumile commented on hotels.html
> +          <p class="no-spam-hotels">Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
Заголовку и абзацу здесь точно нужны особые классы? Если это из-за белого/черного цвета текста, то его можно прописать родителю - потомки унаследуют, и особые классы не понадобятся.

2023-02-12 16:35 UTC, jumile commented on hotels.html
> +            <input class="your-email" type="text" id="user-email" name="user-email" placeholder="Ваш e-mail" required>
тип поля лучше email, оно же для почты, предпочтительнее использовать спец. тип

2023-02-12 16:35 UTC, jumile commented on index.html
> +      <p class="infrastructure-reasons-view">Опытный персонал и качественное обслуживание!</p>
Напрасно ты здесь отступ добавила, ведь у этого абзаца - тот же уровень, что у h2, у них общий родитель. Форматировать код лучше с помощью EditorConfig - и быстрее, и надежнее, он сам все отступы расставит.

2023-02-12 16:35 UTC, jumile commented on styles/styles.css
> +  background-color: #ffffff;;
Лишняя точка с запятой.

2023-02-12 16:35 UTC, jumile commented on styles/styles.css
> +  text-align: center
А здесь не хватает ;

2023-02-12 16:35 UTC, jumile commented on styles/styles.css
> +  color: black;
По кодгайду, цвета нужно писать единообразно - 16-теричными значениями, а если есть прозрачность, то rgba().

2023-02-12 16:35 UTC, jumile commented on styles/styles.css
> +    color: #000000, 0.6;
Если имелся в виду полупрозрачный черный, то он пишется так: rgba(0, 0, 0, 0.6)

2023-02-12 17:20 UTC, LusienLiu commented on hotels.html
> +          <p class="no-spam-hotels">Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
какому родителю здесь можно прописать текст? Subscribe? у него и фон и цвет, a еще в странице отелей- два разных цвета #000000 и #333333. Я не могу сообразить, как это сделать без создания особого класса

2023-02-12 17:50 UTC, LusienLiu commented on index.html
> +      <p class="infrastructure-reasons-view">Опытный персонал и качественное обслуживание!</p>
расскажи на нашем следующем созвоне про этот Editor. Видео по ссылке непонятно процентов на 70

2023-02-13 07:37 UTC, jumile commented on hotels.html
> +          <p class="no-spam-hotels">Только полезная информация и никакого спама,<br>честное бойскаутское!</p>
> какому родителю здесь можно прописать текст? Subscribe? у него и фон и цвет, a еще в странице отелей- два разных цвета #000000 и #333333. Я не могу сообразить, как это сделать без создания особого класса
Да, subscribe. А вот там, где особый цвет, придется сделать класс, по-другому не получится.

2023-02-14 09:03 UTC, merged